name: Tests
description: A GitHub Action to run tests on push and PRs on the main branch

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: echo 'Removing old node_modules...'
      - run: rm -rf node_modules
      - run: echo 'Running yarn install...'
      - run: yarn install --frozen-lockfile
      - run: echo 'Running tests...'
      - run: yarn test
